<?php

use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use Armoredcore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$data = data::get('data');

Layout::includeLayout('header') ?>
<div class="container-fluid">
    <div class="row">


        <div class="col-md-3 side-bar-ingame">
            <div class="row text-center nav-side-bar-ingame">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="<?= URL::toRoute('home/index') ?>"">Voltar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9 ">
            <div class="row" style="height: 10vh;margin-top: 10vh;">
                <div class="col-md-3 ">
                </div>
                <div class="col-md-6" style="justify-content: center;align-items: center;text-align: center;">
                    <h2>LEADERBOARD</h2>
                </div>
                <div class="col-md-3 ">
                </div>
            </div>
            <div class="row" style="height: 20vh;margin-top: 5vh;">
                <div class="col-md-2 ">
                </div>

                <div class="col-md-8" style="height:55vh;justify-content: center;align-items: center;text-align: center;overflow-x: hidden;overflow-y: scroll;">
                    <table style="width: 100%;text-align: center;">
                        <tr>
                            <th scope="col"><h3>Username</h3></th>
                            <td scope="col"><h3>Pontos</h3></td>
                        </tr>
                    <?php
                    $count = count($data);
                    for($i=0;$i<=9;$i++){
                        if ($count==$i){
                            break;
                            }
                            echo '
                                <tr>
                                <th scope="col"><h4>'.strtoupper($data[$i]->user).'</h4></th>
                                <td scope="col"><h4>'.$data[$i]->pontos.'</h4></td>
                                </tr>
                                ';
                    }

                    ?>
                </table>

                </div>
                <div class="col-md-2 ">
                </div>
            </div>


        </div>
    </div>

</div>

