<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
?>
<div class="cube-container">

<div class="dice">
                    <div class="front face">
                        <div>
                            <h1>Shut<br> the<br> Box</h1>
                        </div>
                    </div>
                    <div class="left face">
                        <div>
                            <h3>Marcos Ferreira<br><br>Helder Abrantes<br><br>Rui Agostinho</h3>
                        </div>
                    </div>
                    <div class="right face">
                        <div>
                            <h3>Programação<br><br>para a Web<br><br>Servidor</h3>
                        </div>
                    </div>
                    <div class="back face">
                        <div>
                            <img src="<?=Asset::image('ipl.png')?>">
                        </div>
                    </div>
                </div>

</div>