<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use Armoredcore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;

$data = data::get('data');
$pontos = data::get('pontos');
$error = Data::get('error');

Layout::includeLayout('header') ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 side-bar-ingame">
            <div class="row text-center nav-side-bar-ingame" >
                <?=Layout::includeLayout('sideBarPerfil') ?>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row" style="height: 15vh;margin-top: 5vh;">
                <div class="col-md-3 " style="justify-content: center;align-items: center;text-align: center;">
                    <h3><p>Você fez:<br><br>
                    <?php  echo $pontos;?> pontos</p></h3>
                </div>
                <div class="col-md-6" style="justify-content: center;align-items: center;text-align: center;">
                    <h2>Conquistas</h2>
                </div>
                <div class="col-md-3 ">
                </div>
            </div>
            <div class="row" style="margin-top: 5vh;">
                <div class="col-md-2 ">
                </div>

                <div class="col-md-8" style="height:55vh;justify-content: center;align-items: center;text-align: center;overflow-x: hidden;overflow-y: scroll;">
                    <table style="width: 100%;text-align: center;">
                        <tr>
                            <th scope="col"><h3>#</h3></th>
                            <td scope="col"><h3>Pontos</h3></td>
                            <td scope="col"><h3>Data</h3></td>
                        </tr>
                         <?php
                         $i = 1;
                        foreach($data as $jogo){
                            echo '
                                    <tr>
                                    <th scope="col"><h4>'. $i.'</h4></th>
                                    <td scope="col"><h4>'.$jogo->pontos.'</h4></td>
                                    <td scope="col"><h4>'.date_format($jogo->date," H:i:s Y/m/d").'</h4></td>
                                    </tr>
                                    ';
                            $i++;
                        }

                        ?>
                    </table>

                </div>
                <div class="col-md-2 ">
                </div>
            </div>

        </div>
    </div>
</div>